FROM python:3.7-alpine

ENV PYTHONUNBUFFERED 1

COPY ./requirements.txt requirements.txt

RUN pip install -r /requirements.txt

RUN mkdir /backend 
WORKDIR /backend

COPY ./backend /backend

RUN adduser -D user

USER user

WORKDIR /backend

CMD sh -c "python manage.py runserver 0.0.0.0:8000"